### ISSUE TITLE
URL for subscription information is not working

### ISSUE THREAD

**Issue by guntribam** [gp-technical/stack-pack-gpapi#1]
The gpapi uses the following url to get information for subscriptions:

<NAME_OF_API>/gpapi/hierarchy/subscription/<SUBSCRIPTION_ID>

But the URL that provide this info is:

<NAME_OF_API>/hierarchy/subscription/<SUBSCRIPTION_ID>/<USER_TOKEN>

**Comment by biofractal** [comment]
merged fix - thanks
